# Generated by Django 5.0.1 on 2024-03-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contactmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
