# Generated by Django 5.0.1 on 2024-03-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_couponmodel_alter_productimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponmodel',
            options={'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
    ]
